language: python
python:
  - 2.7
  - 3.6
  - 3.7
install:
  - sudo apt-get -y update
  - sudo apt-get -y install python-matplotlib
  - sudo apt-get -y install bedtools
  - pip install nose
  - pip install codecov
  - python setup.py install
  - pip install -r requirements.txt
  - pip install -r requirements-multiprocessing.txt
script:
  - git clone https://github.com/simonsfoundation/kvsstcp
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/kvsstcp
  - python -c "import os; print(repr(os.name))"
  - python -c "import matplotlib.pyplot as plt; print('imported '+plt.__file__)"
  - coverage run --source=inferelator setup.py test
after_success:
  - codecov
after_failure:
  - pwd
  - find .